# Generated by Django 5.2.16 on 2026-07-18 20:57

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=31,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tenant slug must be 2-31 chars: lowercase letter first, then [a-z0-9_].",
                                regex="^[a-z][a-z0-9_]{1,30}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROVISIONING", "Provisioning"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        default="PROVISIONING",
                        max_length=16,
                    ),
                ),
                ("db_alias", models.CharField(max_length=64, unique=True)),
                ("database_dsn", models.CharField(max_length=500)),
                (
                    "deployment_profile",
                    models.CharField(default="shared", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cp_tenant",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("db_alias__startswith", "tenant_")),
                        name="cp_tenant_alias_prefix",
                    )
                ],
            },
        ),
    ]
