# Generated by Django 5.2.16 on 2026-07-18 20:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.CharField(max_length=255)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("SERVICE", "Service"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=8,
                    ),
                ),
                ("operation", models.CharField(db_index=True, max_length=100)),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=255)),
                ("correlation_id", models.CharField(max_length=64)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
