# Generated by Django 5.2.16 on 2026-07-18 21:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AlterModelManagers(
            name="auditevent",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
